### ISSUE TITLE
Convenience Inits

### ISSUE THREAD

**Issue by ghost** [SpriteKitAlliance/SKAButton#2]
It seems redundant to have to specify a color and size when passing in a texture.

```
    let button = SKAButtonSprite(texture:buttonTexture, color:SKColor.clearColor(), size:buttonTexture.size())
```

**Comment by marcJV** [comment]
Most convenience inits from SKASpriteNode work correctly, added 

```
convenience init(texture: SKTexture?, normalMap: SKTexture?) 
```

To handle init with normalMap textures in [c4f63a3](https://github.com/SpriteKitAlliance/SKAButton/commit/c4f63a36e119c063e538c3bd1bd2fcc3f7870298)
