### ISSUE TITLE
Alpha

### ISSUE THREAD

**Issue by ghost** [SpriteKitAlliance/SKAButton#3]
It would be nice if SKAButton's alpha changed when pressing down.

**Comment by marcJV** [comment]
Added colorBlendFactor for state, this will address this issue. There are also shortcuts I added to help make it styled more like a UIButton for quicker setup

Check out:

```
.setAdjustsSpriteOnHighlight()
```

and

```
.setAdjustsSpriteOnDisable()
```

Fixed in [1047cc5](https://github.com/SpriteKitAlliance/SKAButton/commit/1047cc553f0c8e9c73dbbae7e5a7eebd09aea303)
